/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistem_bank.View;

import com.mycompany.sistem_bank.Model.Nasabah;
import com.mycompany.sistem_bank.Service.Bank;
import java.text.NumberFormat;
import javax.swing.JOptionPane;
import java.util.Locale;

public class TransferFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TransferFrame.class.getName());
    private Nasabah nasabah;
    private Bank bank;
    
    public TransferFrame(Bank bank, Nasabah nasabah) {
        initComponents();
        this.bank = bank;
        this.nasabah = nasabah;
        NomorRekening.setEditable(false);
        SaldoSaatini.setEditable(false);
        NamaPenerima.setEditable(false);
        Jumlahtransfer.setEditable(true);
        setTitle("Transfer Antar Rekening");
    
        NomorRekening.setText(
                nasabah.getRekening().getNomorRekening()
        );
        
        NumberFormat rupiah = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));
        rupiah.setMaximumFractionDigits(0);
        rupiah.setMinimumFractionDigits(0);
        SaldoSaatini.setText(
                rupiah.format(nasabah.getRekening().getSaldo())
        );
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NomorRekening = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        SaldoSaatini = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Jumlahtransfer = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        NamaPenerima = new javax.swing.JTextField();
        Cari = new javax.swing.JButton();
        Transfer = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        NomorRekeningTujuan = new javax.swing.JTextField();
        Batal1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel1.setText("Form transfer");

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel2.setText("Rekening Pengirim");

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel3.setText("Saldo saat ini");

        NomorRekening.addActionListener(this::NomorRekeningActionPerformed);

        jLabel4.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel4.setText("Nomor rekening");

        SaldoSaatini.addActionListener(this::SaldoSaatiniActionPerformed);

        jLabel5.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel5.setText("Rekening Tujuan");

        jLabel6.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel6.setText("Nama penerima");

        Jumlahtransfer.addActionListener(this::JumlahtransferActionPerformed);

        jLabel7.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel7.setText("Jumlah transfer");

        NamaPenerima.addActionListener(this::NamaPenerimaActionPerformed);

        Cari.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Cari.setText("Cari");
        Cari.addActionListener(this::CariActionPerformed);

        Transfer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Transfer.setText("Transfer");
        Transfer.addActionListener(this::TransferActionPerformed);

        jLabel8.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jLabel8.setText("Nomor Rekening Tujuan");

        NomorRekeningTujuan.addActionListener(this::NomorRekeningTujuanActionPerformed);

        Batal1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Batal1.setText("Batal");
        Batal1.addActionListener(this::Batal1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(NomorRekening, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(SaldoSaatini, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(Jumlahtransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(NamaPenerima, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(Transfer, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Batal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NomorRekeningTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Cari))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel1)))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NomorRekening, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SaldoSaatini, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomorRekeningTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cari, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NamaPenerima, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jumlahtransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Transfer, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Batal1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NomorRekeningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomorRekeningActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomorRekeningActionPerformed

    private void SaldoSaatiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaldoSaatiniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaldoSaatiniActionPerformed

    private void JumlahtransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumlahtransferActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JumlahtransferActionPerformed

    private void NamaPenerimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaPenerimaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaPenerimaActionPerformed

    private void CariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariActionPerformed
        String nomorTujuan = NomorRekeningTujuan.getText();
        Nasabah penerima = bank.cariRekening(nomorTujuan);
        
        if(penerima != null){
            NamaPenerima.setText(
                penerima.getRekening().getNamaPemilik()
            );
        } else{
            NamaPenerima.setText("");
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Rekening tujuan tidak ditemukan!",
                    "peringatan",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );
        }
    }//GEN-LAST:event_CariActionPerformed

    private void TransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransferActionPerformed
        try{
            String nomorTujuan = NomorRekeningTujuan.getText();
            Nasabah penerima = bank.cariRekening(nomorTujuan);
            
            if(penerima == null){
                JOptionPane.showMessageDialog(this,
                        "Nomor rekening tujuan tidak ditemukan!",
                        "Transfer Gagal",
                        JOptionPane.ERROR_MESSAGE);
                return; 
            }
            NamaPenerima.setText(penerima.getRekening().getNamaPemilik());
            double jumlah = Double.parseDouble(Jumlahtransfer.getText());
            
            if(jumlah <= 0){
                JOptionPane.showMessageDialog(this,
                        "Jumlah transfer harus lebih dari 0!",
                        "Peringatan",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            boolean berhasil = nasabah.getRekening().tarik(jumlah);
            if(!berhasil){
                JOptionPane.showMessageDialog(this,
                        "Saldo tidak mencukupi!",
                        "Transfer Gagal",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            penerima.getRekening().setor(jumlah);
            NumberFormat rupiah = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));
            rupiah.setMaximumFractionDigits(0);
            rupiah.setMinimumFractionDigits(0);
            JOptionPane.showMessageDialog(this,
                    "Tramsfer Berhasil\n" +
                    "Jumlah transfer: " + rupiah.format(jumlah) +
                    "\nSaldo sekarang: " + rupiah.format(nasabah.getRekening().getSaldo()));
                    
            
            DashboardFrame dashboard = new DashboardFrame(bank, nasabah);
            dashboard.setLocationRelativeTo(null);
            dashboard.setVisible(true);
            this.dispose();  
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,
                      "Masukkan jumlah transfer berupa angka!",
                       "Input Salah",
                        JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_TransferActionPerformed

    private void NomorRekeningTujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomorRekeningTujuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomorRekeningTujuanActionPerformed

    private void Batal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Batal1ActionPerformed
        DashboardFrame dashboard = new DashboardFrame(bank,nasabah);
        dashboard.setLocationRelativeTo(null);
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Batal1ActionPerformed

    public static void main(String args[]) {
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Batal1;
    private javax.swing.JButton Cari;
    private javax.swing.JTextField Jumlahtransfer;
    private javax.swing.JTextField NamaPenerima;
    private javax.swing.JTextField NomorRekening;
    private javax.swing.JTextField NomorRekeningTujuan;
    private javax.swing.JTextField SaldoSaatini;
    private javax.swing.JButton Transfer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
